### PR TITLE
Rust/Diesel: Introduce error messages for cases when internal server error is raised

### LINKED ISSUE #40: Better error messages in rust/diesel
In many cases, if an error occurs using the rust/diesel example ORM, the cause of the error will not be displayed to the user. Instead the app will panic, displaying something along the lines of: `panicked at 'called "Option::unwrap()" on a "None" value'`. Ideally we should propagate the causes of errors to the api, and display them "nicely" with logging (rather than panics).

### PR DESCRIPTION
**Pull request by svranesevic**
I opted for returning `Result<..., String>` as I did not want to return concrete diesel errors (Read - leaky abstractions). Returned string contains user friendly error message.

Closes #40

### CODE REVIEW

File: rust/diesel/src/user.rs [hunk 1]
```diff
@@ -24,29 +24,38 @@ pub struct NewUser {
...
-        update_result.map(|_| user).ok()
+
+        match update_result {
+            Err(diesel::result::Error::NotFound) | Ok(0) => Ok(None),
+            Err(err) => Err(err.to_string()),
+            Ok(_) => Ok(Some(user)),
+        }
     }
 
     pub fn delete(id: i32, connection: &PgConnection) -> bool {
```
Comment (srhickma) [inline rust/diesel/src/user.rs]: This function (and the associated api function) should also return results.

File: rust/diesel/src/product.rs [hunk 2]
```diff
@@ -25,29 +25,42 @@ pub struct NewProduct {
...
-        update_result.map(|_| product).ok()
+
+        match update_result {
+            Err(diesel::result::Error::NotFound) | Ok(0) => Ok(None),
+            Err(err) => Err(err.to_string()),
+            Ok(_) => Ok(Some(product)),
+        }
     }
 
     pub fn delete(id: i32, connection: &PgConnection) -> bool {
```
Comment (srhickma) [inline rust/diesel/src/product.rs]: This function (and the associated api function) should also return results.

File: rust/diesel/src/order.rs [hunk 3]
```diff
@@ -129,15 +148,15 @@ impl Order {
...
         let new_order = NewOrder {
             user_id: order.user_id,
             order_total,
         };
 
-        Some((new_order, product_units))
+        Ok((new_order, product_units))
     }
 
     fn create_order_lines(order: &Order, product_units: Vec<(Product, i16)>) -> Vec<NewOrderLine> {
```
Comment (srhickma) [inline rust/diesel/src/order.rs]: I can't leave a comment on it, but the `delete` function below should also return a result, in this case it would be `Result<(), ErrorType>`.

File: rust/diesel/src/order.rs [hunk 4]
```diff
@@ -50,10 +50,9 @@ pub struct ProductOrder {
 }
 
 impl Order {
-    pub fn create(order: NewUserOrder, connection: &PgConnection) -> Option<Order> {
+    pub fn create(order: NewUserOrder, connection: &PgConnection) -> Result<Order, String> {
```
Comment (srhickma) [inline rust/diesel/src/order.rs]: Nit: you can use `Box<dyn Error>` as your error type if you want to keep the type generic without converting all errors into strings, then just use `.map_err(|err| err.into())` instead of `.map_err(|err| err.to_string())`. It doesn't make much of a difference here, but it is good practice.

Same thing with users and products.

File: rust/diesel/src/order.rs [hunk 5]
```diff
@@ -109,16 +115,29 @@ impl Order {
                     .execute(connection)
             });
 
-        update_result.map(|_| order).ok()
+        match update_result {
+            Err(diesel::result::Error::NotFound) | Ok(0) => Ok(None),
```
Comment (srhickma) [inline rust/diesel/src/order.rs]: I'm not super familiar with diesel, but it seems strange that there are two different cases that both mean the same thing here. What does the `0` represent here?

File: rust/diesel/src/order.rs [hunk 6]
```diff
@@ -109,16 +115,29 @@ impl Order {
...
+        order: &NewUserOrder,
+        connection: &PgConnection,
+    ) -> Result<(NewOrder, Vec<(Product, i16)>), String> {
         let product_units: Vec<(Product, i16)> = order
             .products
             .iter()
             .flat_map(|product_ref| {
-                Product::read(product_ref.product_id, connection)
-                    .map(|product| (product, product_ref.units))
+                let ret: Vec<(Product, i16)> = Product::read(product_ref.product_id, connection)
```
Comment (srhickma) [inline rust/diesel/src/order.rs]: Errors that occur when reading the product are being ignored, I don't think that is what we want.
I think you could use something along these lines here:
```
let product_units: Vec<(Product, i16)> = order
            .products
            .iter()
            .map(|product_ref| {
                match Product::read(product_ref.product_id, connection)? {
                    None => Err(Box::new(DbError::NotFound)),
                    Some(product) => Ok((product, product_ref.units)),
                }
            })
            .collect()?;
```

File: rust/diesel/src/order.rs (hunk 3 above)
Comment (svranesevic) [reply rust/diesel/src/order.rs]: I went for the `Result<bool, String>` as I want distinction between "there is no entity with such id" and "error occurred" situations

File: rust/diesel/src/order.rs (hunk 5 above)
Comment (svranesevic) [reply rust/diesel/src/order.rs]: `Ok(x)` means that SQL was executed successfully, where `x` is number of affected rows.
Eg. if an entity selected by SQL does not exist, it will return Ok(0)

File: rust/diesel/src/order.rs (hunk 4 above)
Comment (svranesevic) [reply rust/diesel/src/order.rs]: I agree, it is a good practice , but I would argue to leave it as is due to simplicity.
If you think it is a must, I'll change this part

**Comment by svranesevic** [comment]
@srhickma 
Pushed changes and left few comments/questions

File: rust/diesel/src/order.rs (hunk 5 above)
Comment (srhickma) [reply rust/diesel/src/order.rs]: Ahh I see, that makes sense.

File: rust/diesel/src/order.rs (hunk 4 above)
Comment (srhickma) [reply rust/diesel/src/order.rs]: That makes sense, I think it is fine to leave it as-is then.

File: rust/diesel/src/order_api.rs [hunk 7]
```diff
@@ -16,31 +36,42 @@ pub struct OrdersResponse {
...
+        }
+    }
 }
 
 #[delete("/orders/<order_id>")]
-pub fn delete_order(order_id: i32, connection: db::Connection) {
-    Order::delete(order_id, &connection);
+pub fn delete_order(order_id: i32, connection: db::Connection) -> Result<Option<()>, ApiError> {
+    match Order::delete(order_id, &connection) {
+        Ok(true) => Ok(Some(())),
```
[the remark this answers is not in the document]
Comment (svranesevic) [reply rust/diesel/src/order_api.rs]: Good catch, it is obsolete

**Comment by svranesevic** [comment]
All set for merge
